---
version: "3.2"
services:
  app:
    build: .
    environment:
      PHP_IDE_CONFIG: 'serverName=icanboogie-com'
#      XDEBUG_MODE: develop,debug
    ports:
      - '8020:80'
    volumes:
    - .:/app:delegated
    - ~/.composer:/root/.composer:delegated
    working_dir: /app
