services:

  handler.document.show:
    class: "App\\Application\\Handler\\ShowDocumentHandler"
    arguments:
      - "@template_engines"
      - "https://github.com/ICanBoogie/docs/blob/{version}/{slug}.md"
