<?php

namespace ICanBoogie;

/**
 * @var $content string
 * @var $sidebar string
 * @var $edit_link string
 */

?>

<div class="docs-wrapper container">
	<section class="sidebar">
		<?= $sidebar ?>
	</section>

	<section class="page-inner">
		<article>
			<?= $content ?>
		</article>

		<footer class="article-actions">
			<a class="action-edit" href="<?= escape($edit_link) ?>">Edit this page</a>
		</footer>
	</section>
</div>
