<?php

namespace ICanBoogie;

/**
 * @var $__VARIABLES__ array
 * @var $view \ICanBoogie\View\View
 * @var $content string
 * @var $page_title string
 */

?><!DOCTYPE html>
<html lang="en">
<?= $view->partial('head', $__VARIABLES__) ?>
<body class="<?= empty($page_id) ? '' : "page--$page_id" ?>">

<?= $view->partial('navigation') ?>
<?= $content ?>
<?= $view->partial('footer') ?>

</body>
</html>
