<nav class="navbar">
	<div class="navbar-brand">
		<a href="/">ICanBoogie</a>
	</div>

	<ul class="nav navbar-nav">
		<li class="nav-item"><a class="nav-link" href="/docs">Documentation</a></li>
		<li class="nav-item"><a class="nav-link" href="#">Lorem</a></li>
		<li class="nav-item"><a class="nav-link" href="#">News</a></li>
		<li class="nav-item"><a class="nav-link" href="#">Ipsum</a></li>
		<li class="nav-item"><a class="nav-link" href="#">Dolor</a></li>
	</ul>

	<!--div class="switcher">
		<div class="dropdown">
			<button class="btn dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
				5.3
				<span class="caret"></span>
			</button>
			<ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
				<li role="presentation">
					<a role="menuitem" tabindex="-1" href="https://laravel.com/docs/master">Master</a>
				</li>
				<li role="presentation">
					<a role="menuitem" tabindex="-1" href="https://laravel.com/docs/5.3">5.3</a>
				</li>
				<li role="presentation">
					<a role="menuitem" tabindex="-1" href="https://laravel.com/docs/5.2">5.2</a>
				</li>
				<li role="presentation">
					<a role="menuitem" tabindex="-1" href="https://laravel.com/docs/5.1">5.1</a>
				</li>
				<li role="presentation">
					<a role="menuitem" tabindex="-1" href="https://laravel.com/docs/5.0">5.0</a>
				</li>
				<li role="presentation">
					<a role="menuitem" tabindex="-1" href="https://laravel.com/docs/4.2">4.2</a>
				</li>
			</ul>
		</div>
	</div-->

	<!--div class="responsive-sidebar-nav">
		<a href="#" class="toggle-slide menu-link btn">☰</a>
	</div-->
</nav>
